# 最终可部署版 wrangler.toml（无任何冗余配置）
name = "libretv"  # 与 CI 系统预期名称一致，消除警告
main = "worker.js"
compatibility_date = "2024-09-03"  # 保留兼容日期，删除过时标志

# 环境变量（已配置 PASSWORD，代理鉴权生效）
[vars]
PASSWORD = "yanyixingfu"  # 日志中已显示你的密码，无需修改
CACHE_TTL = "86400"
MAX_RECURSION = "5"
DEBUG = "false"

# 静态资源目录（指向 LibreTV 根目录）
[site]
bucket = "./"

# 无 [routes] 配置，部署后手动添加（避免语法问题）

