# wrangler.toml 关键关配置（已在之前的最终版中包含）
name = "libretv"
main = "worker.js"
compatibility_date = "2024-09-03"

# 静态资源配置：bucket 指向你的文件目录（如 LibreTV 根目录，含 index.html）
[site]
bucket = "./"  # 本地静态件目录，./ 表示项目根目录
# 可选：exclude 用于排除不需要上传的文件（如 node_modules、日志文件）
exclude = ["node_modules/**/*", "*.log", ".git/**/*"]

# 环境变量（已配置，无需修改）
[vars]
PASSWORD = "yanyixingfu"
CACHE_TTL = "86400"
