# 1. 基础配置（无语法错误，直接保留）
name = "libretv-worker"
main = "worker.js"
compatibility_date = "2024-09-03"
compatibility_flags = ["streams_enable_constructors"]

# 2. 环境变量（替换 PASSWORD 为你的实际密码）
[vars]
PASSWORD = "yanyixingfu"  # 示例：替换为你的鉴权密码，如 123456 或 abc123
CACHE_TTL = "86400"
MAX_RECURSION = "5"
DEBUG = "false"

# 3. 静态资源目录（指向项目根目录，不可改）
[site]
bucket = "./"

# 4. 路由配置（关键：数组格式，严格注意以下3点）
# ① [routes] 下单独一行写 "- pattern = ..."，"-" 前无任何字符（顶格）
# ② "pattern" 和 "zone_name" 用英文引号，等号前后各1个空格
# ③ 注释用英文 #，避免中文符号（如全角空格、中文#）
[routes]
- pattern = "libretv1.yanyixingfu.top/*"  # 你的子域名，如 libretv1.yanyixingfu.top
  zone_name = "yanyixingfu.top"          # 你的主域名，如 yanyixingfu.top（无 www）
