# 1. 基础配置（Wrangler 4.x 兼容格式）
name = "libretv-worker"
main = "worker.js"
compatibility_date = "2024-09-03"
compatibility_flags = ["streams_enable_constructors"]

# 2. 环境变量（必须设置 PASSWORD，否则代理鉴权失败）
[vars]
PASSWORD = "yanyixingfu"  # 替换为你的实际密码（如 123456 或 mytv888）
CACHE_TTL = "86400"
MAX_RECURSION = "5"
DEBUG = "false"

# 3. 静态资源目录（指向 LibreTV 根目录，含 index.html）
[site]
bucket = "./"

# 注意：已删除 [routes] 配置，部署后手动添加路由（避免语法错误）
